spring:
    datasource:
        url: jdbc:mariadb://localhost:3307/student_management
        username: root
        password: 382526
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect

# Cấu hình MyBatis
mybatis:
    mapper-locations: classpath:mappers/*.xml
    configuration:
        map-underscore-to-camel-case: true
